### PR TITLE
Change final calculation logic to ignore skipped

### PR DESCRIPTION
**Pull request by mike-schenk**
I would suggest the logic should be changed to the following

1. looking for any Failed conclusions and if found the conclusion is set to `failure`
2. looking for any Cancelled conclusions and if found the conclusion is set to `cancelled`
3. looking for any Successful conclusions and if found the conclusion is set to `success`
4. If none of the statuses are found, it will set the workflow conclusion to the fallback value which defaults to `skipped`

I want my workflow to skip certain jobs based on which files actually changed in a PR branch, and I want to use the result of workflow-conclusion to control my final status check used for branch protection.

For example, I have a job to build, test, and publish my database migrations, but only when there are changes in them. I have another job to build, test, and publish my web app. In a PR with no database changes, the database migrations job is skipped, so I want the workflow-conclusion to be controlled by the conclusion of the job that _did_ run. With the logic as it is, the workflow-conclusion will say 'skipped' regardless of whether the other job succeeds or fails.

I think we can expect jobs that are skipped are always _intentionally_ skipped because their result is not applicable to the workflow run, and so shouldn't be considered important to workflow-conclusion. If a job reports skipped because of a cancelled workflow run, then the overall result will probably be cancelled anyway. If there's some circumstance where a cancelled workflow will show some successful job and _no_ cancelled jobs, that seems like a GitHub bug, or at least a rare edge case. I.e. how is the current job even running if the workflow is already cancelled?

### CODE REVIEW

**Comment by mike-schenk** [comment]
@im-open/swat, I'm looking for some feedback on this PR.

The problem it's meant to solve is demonstrated by the action run: https://github.com/im-enrollment/account-management/actions/runs/1546618274.

The workflow performed exactly as intended. It skipped some jobs that didn't apply to that particular run and otherwise succeeded, but the `workflow-conclusion` action in the `finish-build` job reported `skipped`.

**Comment by hpractv** [comment]
> The workflow performed exactly as intended. It skipped some jobs that didn't apply to that particular run and otherwise succeeded, but the `workflow-conclusion` action in the `finish-build` job reported `skipped`.

So, the main difference here is that we _don't_ want `skipped` to factor into success or failure, and we want `failure` to take precedence over `cancel` in the final results?

**Comment by danielle-casella-adams** [comment]
I actually think cancelled should take precedence over the failure and in your scenarios that wouldn't disrupt anything.  If I cancel something I don't care if any of the jobs failed, I just want to know that it was cancelled.

I think I'm ok removing 'skipped' from the check so it defaults to skipped if nothing else matches.  With the logic change:

- The readme would need to be updated at the top so the way it describes how it works now
- The version on the readme needs to be updated.  I think this would be a major change since it's changing the way it works so it would need a commit message to reflect that.
- The changes need to be recompiled with an `npm run build`

**Comment by mike-schenk** [comment]
> I actually think cancelled should take precedence over the failure and in your scenarios that wouldn't disrupt anything. If I cancel something I don't care if any of the jobs failed, I just want to know that it was cancelled.
> 
> I think I'm ok removing 'skipped' from the check so it defaults to skipped if nothing else matches. With the logic change:
> 
> * The readme would need to be updated at the top so the way it describes how it works now
> * The version on the readme needs to be updated.  I think this would be a major change since it's changing the way it works so it would need a commit message to reflect that.
> * The changes need to be recompiled with an `npm run build`

I don't have a strong feeling about the relative precedence of 'failed' vs 'cancelled', so that's fine.

I can make that change and the others identified here.

**Review by danielle-casella-adams — APPROVED** [review]

**Pull request merged**
